# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformTaskV4@4
    inputs:
      provider: "azurerm"
      command: "init"
      backendServiceArm: "storage-sc"
      backendAzureRmResourceGroupName: "powershell-grp"
      backendAzureRmStorageAccountName: "terraformstate201121"
      backendAzureRmContainerName: "appstore400089891210"
      backendAzureRmKey: "terraform.tfstate"
      workingDirectory: '$(System.DefaultWorkingDirectory)/'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'storage-sc'
      workingDirectory: '$(System.DefaultWorkingDirectory)/'
      
  # - task: TerraformTaskV4@4
  #   inputs:
  #     provider: 'azurerm'
  #     command: 'apply'
  #     environmentServiceNameAzureRM: 'azure-connection'
  #     workingDirectory: '$(System.DefaultWorkingDirectory)/'
      
